font_family JetBrainsMono Nerd Font Mono Bold
font_size 16
enable_audio_bell no
window_padding_width 8

# open new pane horizontally 
map command+; send_text all \x01\x22
# open new pane vertically
map command+shift+; send_text all \x01\x25

# resize panes
map ctrl+h send_text all \x01\x1b\x5b\x31\x3b\x33\x44
map ctrl+k send_text all \x01\x1b\x5b\x31\x3b\x33\x41
map ctrl+j send_text all \x01\x1b\x5b\x31\x3b\x33\x42
map ctrl+l send_text all \x01\x1b\x5b\x31\x3b\x33\x43

# switch to pane
map alt+h send_text all \x01\x1b\x5b\x44
map alt+k send_text all \x01\x1b\x5b\x41
map alt+j send_text all \x01\x1b\x5b\x42
map alt+l send_text all \x01\x1b\x5b\x43
