[manager]
prepend_keymap = [
  { on   = [ ",", "s" ], run  = "plugin what-size", desc = "Calc size of selection or cwd" },
  { on   = [ ",", "y" ], run  = "plugin system-clipboard", desc = "Copy file to clipboard" },
  { on   = [ ",", "c" ], run  = "plugin ouch", desc = "Compress with ouch" },
]
