set -o vi

# Amazon Q pre block. Keep at the top of this file.
# [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"
# Amazon Q pre block. Keep at the top of this file.

path=(
  $HOME/bin
  $HOME/go/bin
  $HOME/.local/bin
  /usr/local/bin
  /opt/homebrew/bin
  /opt/homebrew/sbin
  $HOME/.nvm/versions/node/v23.11.0/bin
  /Users/leonid/.cache/lm-studio/bin
  /opt/homebrew/opt/crowdin@4/bin
  /opt/homebrew/opt/gnu-sed/libexec/gnubin
  /Library/TeX/texbin
  $path
)

[ -f "$HOME/.secrets.zsh" ] && source "$HOME/.secrets.zsh"
export LM_STUDIO_API_KEY=
export LM_STUDIO_API_BASE=http://localhost:1234/v1/

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git kubectl conda)

source $ZSH/oh-my-zsh.sh
source /opt/homebrew/opt/kube-ps1/share/kube-ps1.sh

KUBE_PS1_SYMBOL_ENABLE=false
KUBE_PS1_NS_ENABLE=false
KUBE_PS1_PREFIX=''
KUBE_PS1_SUFFIX=' '
PS1='$(conda_prompt_info)$(kube_ps1)'$PS1

function kx_fn() {
    local context=$1
    local subscription
    if [[ "$context" = "dev" || "$context" = "exp" ]]; then
        subscription="dev"
    else
        # vpnutil start "DedicatedVPN"
        wgc up
        subscription="prod"
    fi
    az account set --subscription="$subscription"
    kubectx "$context"
}
alias kx="kx_fn"

alias vim="nvim"
alias gtd="git diff"
alias gtc="git commit -m"
alias gtl="git log --pretty=oneline"
alias gpo="git push origin"
alias gts="git status"
alias ll="ls -al"
alias jl="jupyter lab"
alias top="btop"
alias codex="aichat --rag codex --session"

ff() {
  sudo find /Applications /Library /System/Library /Users/$(whoami)/Library /private/var/folders -iname "*$1*" 2>&1 | grep -v 'Operation not permitted'
}

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# sdkman
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
export JAVA_HOME="$HOME/.sdkman/candidates/java/21.0.4-amzn"
export PATH="$HOME/.sdkman/candidates/gradle/8.5/bin:$PATH"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export LUA_CPATH="/opt/homebrew/lib/lua/5.4/?.so;;"

# conda lazy initialization
_conda_lazy_init() {
  unset -f conda

  if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
    . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
  else
    export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
  fi

  conda "$@"
}

conda() {
  _conda_lazy_init "$@"
}

# Amazon Q post block. Keep at the bottom of this file.
# [[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"
